### PR TITLE
Refactor forwarder to use updated Options pattern from sdk-ovs

### PR DESCRIPTION
**Pull request by bszirtes**
## Description

Refactoring forwarder-ovs to use the updated Options patterns from sdk-ovs, just as it has been implemented in the forwarder-vpp.

Depends on: https://github.com/networkservicemesh/sdk-ovs/pull/320
## Issue link

https://github.com/networkservicemesh/sdk-ovs/issues/319

## How Has This Been Tested?

- [ ] Added unit testing to cover
- [X] Tested manually
- [ ] Tested by integration testing
- [ ] Have not tested

## Types of changes

- [ ] Bug fix
- [ ] New functionality
- [ ] Documentation
- [X] Refactoring
- [ ] CI

### CODE REVIEW

**Review by ljkiraly — APPROVED** [review]
Seems good to me

**Comment by denis-tingaikin** [comment]
@bszirtes It seems like CI is stuck. Could you rebase the branch to the latest main and re-push changes?

**Comment by bszirtes** [comment]
@denis-tingaikin I just tried rebasing, and it indicated that everything is up to date. Even though, I did a force-push after the rebasing, but it appears that nothing has changed. Do you have any other suggestions?

**Comment by denis-tingaikin** [comment]
@bszirtes  Looks weird. There might be something on the GitHub actions side. I just pushed a test branch https://github.com/networkservicemesh/cmd-forwarder-ovs/pull/368, and CI has started. Could you try creating a new branch based on this and trying to open it?

**Comment by denis-tingaikin** [comment]
@bszirtes Yes, you may simply use `git switch -c` to create a new branch based on these changes and open a new PR that I expect should fix the CI.

**Comment by denis-tingaikin** [comment]
@bszirtes One second seems like your branch just has conflicts that must be resolved.

**Comment by denis-tingaikin** [comment]
Could you try this?

```bash
git switch refactor-chains-options-pattern
git fetch origin
git rebase -X ours origin/main
git push $forkName refactor-chains-options-pattern -f
```

**Comment by bszirtes** [comment]
@denis-tingaikin I just tried.

**Comment by denis-tingaikin** [comment]
OK, soemthing changed and seems like we're on the right direction 😀

This should repair the branch.

```bash
git branch -m  refactor-chains-options-pattern-tmp
git checkout origin/main
git switch -c refactor-chains-options-pattern
git cherry-pick 885de7831142d881296967b75a74361d1299fb41
git push $forkName refactor-chains-options-pattern -f
```

**Comment by bszirtes** [comment]
@denis-tingaikin I got the following after I executed `git cherry-pick 885de7831142d881296967b75a74361d1299fb41`  :
```
Auto-merging go.mod
CONFLICT (content): Merge conflict in go.mod
Auto-merging go.sum
CONFLICT (content): Merge conflict in go.sum
Auto-merging main.go
CONFLICT (content): Merge conflict in main.go
error: could not apply 885de78... Refactor forwarder to use updated Options pattern from sdk-ovs
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
```
Should I try to resolve these manually?

**Comment by denis-tingaikin** [comment]
Yes, it can be fixed manually; as an alternative, you may do this.

```bash
git cherry-pick --abort
git cherry-pick -X theirs 885de7831142d881296967b75a74361d1299fb41
```

**Comment by bszirtes** [comment]
@denis-tingaikin I just pushed again, but it seems to me that I have even more conflicts somehow. Should I create a new PR with same changes?

**Comment by bszirtes** [comment]
@denis-tingaikin Well, it looks like it passed the checks. Thank you for the assistance!

**Review by denis-tingaikin — APPROVED** [review]
Woot! Problems are fixed 💪

LGTM.

**Pull request merged**
